import localFont from "next/font/local";
import "./globals.css";
import { Header } from "./components/Header"
import { Footer } from "./components/Footer"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export default function RootLayout({ children }) {

  var settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1
  };

  return (
    <html lang="en">      
      <body
        className={`antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
